language:       node_js

node_js:
    - "node"
    - "8.6.0"
    - "7"

sudo:           false

git:
    submodules: false

services: mongodb

before_install:
- export TZ=Europe/Stockholm

before_script:
    - make install

script:
    - make test

notifications:
    email:      false
