version: "2"
services:
    test810:
        build:
            context: .
            dockerfile: docker/node810/dockerfile
        environment:
            - DBWEBB_DSN=mongodb://mongodb:27017/history
        volumes:
            - ./:/app/
            - /app/node_modules/
        links:
            - mongodb
        command: "npm test"
    test830:
        build:
            context: .
            dockerfile: docker/node830/dockerfile
        environment:
            - DBWEBB_DSN=mongodb://mongodb:27017/history
        volumes:
            - ./:/app/
            - /app/node_modules/
        links:
            - mongodb
        command: "npm test"
    test860:
        build:
            context: .
            dockerfile: docker/node860/dockerfile
        environment:
            - DBWEBB_DSN=mongodb://mongodb:27017/history
        volumes:
            - ./:/app/
            - /app/node_modules/
        links:
            - mongodb
        command: "npm test"
    express:
        build:
            context: .
            dockerfile: docker/express/dockerfile
        environment:
            - DBWEBB_DSN=mongodb://mongodb:27017/history
        volumes:
            - ./:/app/
            - /app/node_modules/
        ports:
            - 3000:3000
        links:
            - mongodb
        command: "npm start"

    mongodb:
        image: mongo
        container_name: "mongodb_server"
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod  --bind_ip_all
